//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPWVessel.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationModule
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ModuleCode { get; set; }
        public Nullable<int> AppLicationId { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
