//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPWVessel.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Sid { get; set; }
        public string SName { get; set; }
        public int RollNo { get; set; }
        public int Age { get; set; }
    }
}
