//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPWVessel.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPWVessel.Model.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressAr is Required.
        /// </summary>
        public static string AddressArRequired {
            get {
                return ResourceManager.GetString("AddressArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is Required.
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By Site User Id Required.
        /// </summary>
        public static string ApprovedBySiteUserIdRequired {
            get {
                return ResourceManager.GetString("ApprovedBySiteUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Person Is Required.
        /// </summary>
        public static string AuthorizedPersonIdIsRequired {
            get {
                return ResourceManager.GetString("AuthorizedPersonIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifiacte Number is Required.
        /// </summary>
        public static string CertifiacteNumberisRequired {
            get {
                return ResourceManager.GetString("CertifiacteNumberisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate  Alert Period is Required.
        /// </summary>
        public static string CertificateAlertPeriodisRequired {
            get {
                return ResourceManager.GetString("CertificateAlertPeriodisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Date is Required.
        /// </summary>
        public static string CertificateDateisRequired {
            get {
                return ResourceManager.GetString("CertificateDateisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Expiry Date is Required.
        /// </summary>
        public static string CertificateExpiryDateisRequired {
            get {
                return ResourceManager.GetString("CertificateExpiryDateisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate File is Required.
        /// </summary>
        public static string CertificateFileisRequired {
            get {
                return ResourceManager.GetString("CertificateFileisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Type is Required.
        /// </summary>
        public static string CertificateTypeisRequired {
            get {
                return ResourceManager.GetString("CertificateTypeisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name is Required.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City NameAr is Required.
        /// </summary>
        public static string CityNameAr {
            get {
                return ResourceManager.GetString("CityNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client AddressAr is Required.
        /// </summary>
        public static string ClientAddressArisRequired {
            get {
                return ResourceManager.GetString("ClientAddressArisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Address is Required.
        /// </summary>
        public static string ClientAddressisRequired {
            get {
                return ResourceManager.GetString("ClientAddressisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Email is Required.
        /// </summary>
        public static string ClientEmailisRequired {
            get {
                return ResourceManager.GetString("ClientEmailisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client NameAr is Required.
        /// </summary>
        public static string ClientNameArisRequired {
            get {
                return ResourceManager.GetString("ClientNameArisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name is Required.
        /// </summary>
        public static string ClientNameisRequired {
            get {
                return ResourceManager.GetString("ClientNameisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is Required.
        /// </summary>
        public static string CommentisRequired {
            get {
                return ResourceManager.GetString("CommentisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company NameAr is Required.
        /// </summary>
        public static string CompanyNameArisRequired {
            get {
                return ResourceManager.GetString("CompanyNameArisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name is Required.
        /// </summary>
        public static string CompanyNameisRequired {
            get {
                return ResourceManager.GetString("CompanyNameisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact PersonAr is Required.
        /// </summary>
        public static string ContactPersonArisRequired {
            get {
                return ResourceManager.GetString("ContactPersonArisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person is Required.
        /// </summary>
        public static string ContactPersonisRequired {
            get {
                return ResourceManager.GetString("ContactPersonisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Alert Period is Required.
        /// </summary>
        public static string ContractAlertPeriodisrequired {
            get {
                return ResourceManager.GetString("ContractAlertPeriodisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Copy Required.
        /// </summary>
        public static string ContractCopyRequired {
            get {
                return ResourceManager.GetString("ContractCopyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Date is Required.
        /// </summary>
        public static string ContractDateisRequired {
            get {
                return ResourceManager.GetString("ContractDateisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date is Required.
        /// </summary>
        public static string ContractExpiryDateisRequired {
            get {
                return ResourceManager.GetString("ContractExpiryDateisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract File is Required.
        /// </summary>
        public static string ContractFileisRequired {
            get {
                return ResourceManager.GetString("ContractFileisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number is Required.
        /// </summary>
        public static string ContractNumberisRequired {
            get {
                return ResourceManager.GetString("ContractNumberisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractors NameAr is Required.
        /// </summary>
        public static string ContractorsNameArisRequired {
            get {
                return ResourceManager.GetString("ContractorsNameArisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractors Name is Required.
        /// </summary>
        public static string ContractorsNameisRequired {
            get {
                return ResourceManager.GetString("ContractorsNameisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContractSupervisor Is Required.
        /// </summary>
        public static string ContractSupervisor {
            get {
                return ResourceManager.GetString("ContractSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Supervisor Is Required.
        /// </summary>
        public static string ContractSupervisorId {
            get {
                return ResourceManager.GetString("ContractSupervisorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type is Required.
        /// </summary>
        public static string ContractTypeisRequired {
            get {
                return ResourceManager.GetString("ContractTypeisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedAt Is Required.
        /// </summary>
        public static string CreatedAtIsRequired {
            get {
                return ResourceManager.GetString("CreatedAtIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedBy Person is Required.
        /// </summary>
        public static string CreatedByIsRequired {
            get {
                return ResourceManager.GetString("CreatedByIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By Site User Id Required.
        /// </summary>
        public static string CreatedBySiteUserIdRequired {
            get {
                return ResourceManager.GetString("CreatedBySiteUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Logo is Required.
        /// </summary>
        public static string CustomerLogoRequired {
            get {
                return ResourceManager.GetString("CustomerLogoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From is Required.
        /// </summary>
        public static string DateFromRequired {
            get {
                return ResourceManager.GetString("DateFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To  is Required.
        /// </summary>
        public static string DateToRequired {
            get {
                return ResourceManager.GetString("DateToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Email is Required.
        /// </summary>
        public static string DepartmentEmail {
            get {
                return ResourceManager.GetString("DepartmentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Head is Required.
        /// </summary>
        public static string DepartmentHead {
            get {
                return ResourceManager.GetString("DepartmentHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department HeadAr is Required.
        /// </summary>
        public static string DepartmentHeadAr {
            get {
                return ResourceManager.GetString("DepartmentHeadAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name is Required.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department NameAr is Required.
        /// </summary>
        public static string DepartmentNameAr {
            get {
                return ResourceManager.GetString("DepartmentNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc Is Required.
        /// </summary>
        public static string DescIsRequired {
            get {
                return ResourceManager.GetString("DescIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescriptionAr  is Required.
        /// </summary>
        public static string DescriptionArRequired {
            get {
                return ResourceManager.GetString("DescriptionArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description  is Required.
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration is Required.
        /// </summary>
        public static string DurationRequired {
            get {
                return ResourceManager.GetString("DurationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string Electricity {
            get {
                return ResourceManager.GetString("Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmergencyEquipment Is Required.
        /// </summary>
        public static string EmergencyEquipmentIdIsRequired {
            get {
                return ResourceManager.GetString("EmergencyEquipmentIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment is Required.
        /// </summary>
        public static string EquipmentIdIsRequired {
            get {
                return ResourceManager.GetString("EquipmentIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date is Required.
        /// </summary>
        public static string ExpiryDateRequired {
            get {
                return ResourceManager.GetString("ExpiryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirePrecaution Is required.
        /// </summary>
        public static string FirePrecautionIdIsRequired {
            get {
                return ResourceManager.GetString("FirePrecautionIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Precaution Namei Ar is Required.
        /// </summary>
        public static string FirePrecautionNameArisRequired {
            get {
                return ResourceManager.GetString("FirePrecautionNameArisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Precaution Name is Required.
        /// </summary>
        public static string FirePrecautionNameisRequired {
            get {
                return ResourceManager.GetString("FirePrecautionNameisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FireRiskManagement.
        /// </summary>
        public static string FireRiskManagement {
            get {
                return ResourceManager.GetString("FireRiskManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Number is Required.
        /// </summary>
        public static string FloorNumbers {
            get {
                return ResourceManager.GetString("FloorNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName Ar Required.
        /// </summary>
        public static string FullNameArRequired {
            get {
                return ResourceManager.GetString("FullNameArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName is Required.
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard Name Ar is Required.
        /// </summary>
        public static string HazardNameArisRequired {
            get {
                return ResourceManager.GetString("HazardNameArisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard Name is Required.
        /// </summary>
        public static string HazardNameisRequired {
            get {
                return ResourceManager.GetString("HazardNameisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard Probability NameAr is Required.
        /// </summary>
        public static string HazardProbabilityNameArisRequired {
            get {
                return ResourceManager.GetString("HazardProbabilityNameArisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard Probability Name is Required.
        /// </summary>
        public static string HazardProbabilityNameisRequired {
            get {
                return ResourceManager.GetString("HazardProbabilityNameisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard Severity Name Ar is Required.
        /// </summary>
        public static string HazardSeverityNameArisRequired {
            get {
                return ResourceManager.GetString("HazardSeverityNameArisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard Severity Name is Required.
        /// </summary>
        public static string HazardSeverityNameisRequired {
            get {
                return ResourceManager.GetString("HazardSeverityNameisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is Required.
        /// </summary>
        public static string ImageRequired {
            get {
                return ResourceManager.GetString("ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user or password.
        /// </summary>
        public static string Invaliduserorpassword {
            get {
                return ResourceManager.GetString("Invaliduserorpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssuedBy Person is Required.
        /// </summary>
        public static string IssuedByIsRequired {
            get {
                return ResourceManager.GetString("IssuedByIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item NameAr  is Required.
        /// </summary>
        public static string ItemNameArRequired {
            get {
                return ResourceManager.GetString("ItemNameArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name  is Required.
        /// </summary>
        public static string ItemNameRequired {
            get {
                return ResourceManager.GetString("ItemNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Performer Is Required.
        /// </summary>
        public static string JobPerformIdIsRequired {
            get {
                return ResourceManager.GetString("JobPerformIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind Of Work is Required.
        /// </summary>
        public static string KindOfWorkRequired {
            get {
                return ResourceManager.GetString("KindOfWorkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitute is Required.
        /// </summary>
        public static string Latitute {
            get {
                return ResourceManager.GetString("Latitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Floor is Required.
        /// </summary>
        public static string LocationFloorisRequired {
            get {
                return ResourceManager.GetString("LocationFloorisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is Required.
        /// </summary>
        public static string LocationIdIsRequired {
            get {
                return ResourceManager.GetString("LocationIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Id is Required.
        /// </summary>
        public static string LocationIdRequired {
            get {
                return ResourceManager.GetString("LocationIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is Required.
        /// </summary>
        public static string LocationisRequired {
            get {
                return ResourceManager.GetString("LocationisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name is Required.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name is RequiredAr.
        /// </summary>
        public static string LocationNameAr {
            get {
                return ResourceManager.GetString("LocationNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longtitute is Required.
        /// </summary>
        public static string Longtitute {
            get {
                return ResourceManager.GetString("Longtitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes is Required.
        /// </summary>
        public static string NotesRequired {
            get {
                return ResourceManager.GetString("NotesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldPassword.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Head NameAr is Required.
        /// </summary>
        public static string OrganizationHeadNameArRequired {
            get {
                return ResourceManager.GetString("OrganizationHeadNameArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Head Name is Required.
        /// </summary>
        public static string OrganizationHeadNameRequired {
            get {
                return ResourceManager.GetString("OrganizationHeadNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Id is Required.
        /// </summary>
        public static string OrganizationIdRequired {
            get {
                return ResourceManager.GetString("OrganizationIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization is Required.
        /// </summary>
        public static string OrganizationisRequired {
            get {
                return ResourceManager.GetString("OrganizationisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization NameAr is Required.
        /// </summary>
        public static string OrganizationNameArRequired {
            get {
                return ResourceManager.GetString("OrganizationNameArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name is Required.
        /// </summary>
        public static string OrganizationNameRequired {
            get {
                return ResourceManager.GetString("OrganizationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 6 characters long..
        /// </summary>
        public static string Passwordlength {
            get {
                return ResourceManager.GetString("Passwordlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string Passwordnotmatched {
            get {
                return ResourceManager.GetString("Passwordnotmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Issued To Is Required.
        /// </summary>
        public static string PermitIssuedToRequired {
            get {
                return ResourceManager.GetString("PermitIssuedToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Valid From Is Required.
        /// </summary>
        public static string PermitValidFromIsRequired {
            get {
                return ResourceManager.GetString("PermitValidFromIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermitValidTo Is Required.
        /// </summary>
        public static string PermitValidToIsRequired {
            get {
                return ResourceManager.GetString("PermitValidToIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is Required.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyDamage.
        /// </summary>
        public static string PropertyDamage {
            get {
                return ResourceManager.GetString("PropertyDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Required.
        /// </summary>
        public static string ReasonRequired {
            get {
                return ResourceManager.GetString("ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Name.
        /// </summary>
        public static string RecipientName {
            get {
                return ResourceManager.GetString("RecipientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name is Required.
        /// </summary>
        public static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region NameAr is Required.
        /// </summary>
        public static string RegionNameAr {
            get {
                return ResourceManager.GetString("RegionNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Precaution is Required.
        /// </summary>
        public static string SafetyPrecautionRequired {
            get {
                return ResourceManager.GetString("SafetyPrecautionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        public static string Snapshot {
            get {
                return ResourceManager.GetString("Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is Required.
        /// </summary>
        public static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierNameAr is Required.
        /// </summary>
        public static string SupplierNameArisRequired {
            get {
                return ResourceManager.GetString("SupplierNameArisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name is Required.
        /// </summary>
        public static string SupplierNameisRequired {
            get {
                return ResourceManager.GetString("SupplierNameisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Type is Required.
        /// </summary>
        public static string TicketTypeisRequired {
            get {
                return ResourceManager.GetString("TicketTypeisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolBox.
        /// </summary>
        public static string ToolBox {
            get {
                return ResourceManager.GetString("ToolBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdatedBy Person is Required.
        /// </summary>
        public static string UpdatedByIsRequired {
            get {
                return ResourceManager.GetString("UpdatedByIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string UserDetais {
            get {
                return ResourceManager.GetString("UserDetais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is Required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserType is Required.
        /// </summary>
        public static string UserTypeRequired {
            get {
                return ResourceManager.GetString("UserTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Company Details.
        /// </summary>
        public static string VisitorCompanyDetails {
            get {
                return ResourceManager.GetString("VisitorCompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Name is  Required.
        /// </summary>
        public static string WorkNameIsRequired {
            get {
                return ResourceManager.GetString("WorkNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Supervisor Is Required.
        /// </summary>
        public static string WorkSupervisorRequired {
            get {
                return ResourceManager.GetString("WorkSupervisorRequired", resourceCulture);
            }
        }
    }
}
